server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/light_crud
    username: root
    password: vic02139450!
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: dndhkanjsrkgoTsmsepdlfjgrptkdydgksmsrjrnsk
  accessTokenExpiration: 36000000
  refreshTokenExpiration: 60480000




management:
  endpoints:
    web:
      exposure:
        include: health, beans, refresh, info, metrics, prometheus

jasypt:
  encryptor:
    bean: jasyptStringEncryptor